apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: mdb
spec:
  version: {{ .TagName }}
  homepage: https://github.com/hedgieinsocks/kubectl-mdb
  shortDescription: Interact with mariadb-operator semi-sync replication clusters
  description: |
    The plugin simplifies frequent interactions with
    mariadb-operator semi-sync replication clusters
    by using subcommands as aliases for common
    administrative tasks from launching mariadb shell
    to recreating a replica pod from primary data
  caveats: |
    Dependencies: jq
  platforms:
  - selector:
      matchExpressions:
      - key: os
        operator: In
        values:
        - linux
        - darwin
    {{ addURIAndSha "https://github.com/hedgieinsocks/kubectl-mdb/archive/refs/tags/{{ .TagName }}.tar.gz" .TagName }}
    files:
    - from: kubectl-mdb-*/kubectl-mdb
      to: .
    - from: kubectl-mdb-*/LICENSE
      to: .
    bin: "./kubectl-mdb"
