apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: mdba
spec:
  version: {{ .TagName }}
  homepage: https://github.com/hedgieinsocks/kubectl-mdba
  shortDescription: Manage mariadb-operator semi-sync replication clusters
  description: |
    This unofficial plugin helps manage
    mariadb-operator semi-sync replication clusters:
    launch mariadb shell, switch the primary pod,
    recreate a replica pod, etc.
  caveats: |
    Dependencies: jq
  platforms:
  - selector:
      matchExpressions:
      - key: os
        operator: In
        values:
        - linux
        - darwin
    {{ addURIAndSha "https://github.com/hedgieinsocks/kubectl-mdba/archive/refs/tags/{{ .TagName }}.tar.gz" .TagName }}
    files:
    - from: kubectl-mdba-*/kubectl-mdba
      to: .
    - from: kubectl-mdba-*/LICENSE
      to: .
    bin: "./kubectl-mdba"
